### Post request to patients
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "nuwan thushara012",
  "email": "nthrusara012@gmail.com",
  "address": "123 kyle street newyork usa",
  "dateOfBirth": "1999-09-17",
  "registeredDate": "2025-03-20"
}

###